import numpy as np

X_HOME_ENDZONE = 0
X_HOME_10YD = 20
X_AWAY_GOAL_LINE = 110
X_AWAY_ENDZONE = 120
X_NUMBER_SPACING = 10
X_N_NUMBERS = 9
YARD_NUMBERS = list(map(str, list(np.arange(10, 50, X_NUMBER_SPACING)) + list(np.arange(40, 9, -X_NUMBER_SPACING))))

Y_BOTTOM_SIDELINE = 0
Y_TOP_SIDELINE = 53.5
SIDELINE_PADDING = 5

FIELD_COLOR = "#3b8242"
