data:
  train: "./data/nfl-big-data-bowl-2024/play_by_play_train.pkl"
  val: "./data/nfl-big-data-bowl-2024/play_by_play_val.pkl"
  test: "./data/nfl-big-data-bowl-2024/play_by_play_test.pkl"
dataloader_settings:
  num_workers: 2
  batch_size: 8
  persistent_workers: True
model_settings:
  representation_class: "TransformerRepresentor"
  input_size: 248
loss_hparams:
  alpha: 1.0
  beta: 1.0
optimizer_settings:
  name: "Adam"
  params:
    lr: 1.0e-6
trainer_args:
  num_sanity_val_steps: 2
  overfit_batches: 8
  max_epochs: 100
  log_every_n_steps: 10
callbacks:
  #- name: "EarlyStopping" -- this is disabled for debugging by default, but here is something to copy-paste.
  #  params: 
  #    monitor: "val/loss_total_tarreg"
  #    mode: "min"
  #    min_delta: 1.0e-8
  #    patience: 10
  #    verbose: True
  - name: "ModelCheckpoint"
    params:
      save_top_k: 1
      monitor: "global_step"
      mode: "max"
      filename: "model-{epoch:02d}-{global_step}"
